### ISSUE TITLE
Adaptor plate

### ISSUE THREAD

**Issue by totalitarian** [Repl1catorCZ/Predator-Delta-3D-Printer#13]
Do we need to print an adaptor plate to mount the board on the existing standoffs?

**Comment by Repl1catorCZ** [comment]
Hi, Thanks for report. 
Yes you need print a case for board. I doesent have a fit one yet .. just an old one which i use for MKS gen L i will add stl ASAP ..

**Comment by totalitarian** [comment]
Thanks. Just found one in the facebook group that i'm trailing now.

**Comment by Repl1catorCZ** [comment]
@totalitarian if you find or model something awesome we could implement it on base stl .. im not at home this week then i cant help .. but most of  MKS gen L v1 are fit on skr .. but  try to post here some links for thingi .. but better way will be if we model one for us .. after a get home i mesure board and offset for perfect fit ..

**Comment by totalitarian** [comment]
Just modelling one now. I'll report back if it's any good
